#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Tresenraya.Resource", IsApplication=true)]

namespace Tresenraya
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040006
			public const int amraillobajo = 2130968582;
			
			// aapt resource value: 0x7f040001
			public const int azul = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int blanco = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int celeste = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int naranja = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int puzzle_hint_2 = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int puzzle_selected = 2130968584;
			
			// aapt resource value: 0x7f040000
			public const int rojo = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int verdeagua = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int a = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int fondo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int monoandroidsplash = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int o = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int press = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int x = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int FrameLayout01 = 2131165184;
			
			// aapt resource value: 0x7f07000e
			public const int bt_jugar = 2131165198;
			
			// aapt resource value: 0x7f070008
			public const int imageV_cinco = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int imageV_cuatro = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int imageV_dos = 2131165189;
			
			// aapt resource value: 0x7f07000c
			public const int imageV_nueve = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int imageV_ocho = 2131165195;
			
			// aapt resource value: 0x7f070009
			public const int imageV_seis = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int imageV_siete = 2131165194;
			
			// aapt resource value: 0x7f070006
			public const int imageV_tres = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int imageV_uno = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int img_back_portrait = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int linearLayout2 = 2131165186;
			
			// aapt resource value: 0x7f07000d
			public const int tv_jugador = 2131165197;
			
			// aapt resource value: 0x7f070003
			public const int tv_titulo = 2131165187;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Mono_Android_Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
